# Scheduler makefile

sched : controller.cpp cluster_state.cpp cluster_state.h process.cpp process.h lib/binary_heap.h lib/list.h processor.cpp processor.h
	g++ -o sched controller.cpp cluster_state.cpp process.cpp processor.cpp -Wall
